# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 02:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('login_type', models.SmallIntegerField(choices=[(0, 'Email - M\u1eadt kh\u1ea9u'), (1, 'Google'), (2, 'Facebook')], default=0, help_text='Ki\u1ec3u \u0111\u0103ng nh\u1eadp', verbose_name='Ki\u1ec3u \u0111\u0103ng nh\u1eadp')),
                ('reset_pass_key', models.CharField(blank=True, help_text='\u0110\u01b0\u1ee3c t\u1ea1o t\u1ef1 \u0111\u1ed9ng khi ng\u01b0\u1eddi d\xf9ng \u0111\u1eb7t l\u1ea1i m\u1eadt kh\u1ea9u', max_length=255, null=True, verbose_name='Key \u0111\u1eb7t l\u1ea1i m\u1eadt kh\u1ea9u')),
                ('reset_pass_expire', models.DateTimeField(blank=True, help_text='\u0110\u01b0\u1ee3c t\u1ea1o t\u1ef1 \u0111\u1ed9ng khi ng\u01b0\u1eddi d\xf9ng \u0111\u1eb7t l\u1ea1i m\u1eadt kh\u1ea9u', null=True, verbose_name='H\u1ea1n \u0111\u1eb7t l\u1ea1i m\u1eadt kh\u1ea9u')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Tr\u1ea1ng th\xe1i ho\u1ea1t \u0111\u1ed9ng hi\u1ec7n t\u1ea1i c\u1ee7a t\xe0i kho\u1ea3n', verbose_name='\u0110ang ho\u1ea1t \u0111\u1ed9ng')),
                ('is_delete', models.BooleanField(default=False, help_text='B\u1ea3n ghi \u0111\xe3 \u0111\u01b0\u1ee3c xo\xe1 hay ch\u01b0a', verbose_name='\u0110\xe3 xo\xe1')),
                ('is_block', models.BooleanField(default=False, help_text='T\xe0i kho\u1ea3n c\xf3 \u0111ang b\u1ecb kho\xe1 kh\xf4ng', verbose_name='Kho\xe1')),
                ('block_expire', models.DateTimeField(blank=True, help_text='H\u1ea1n kho\xe1 t\xe0i kho\u1ea3n. \u0110\u1ec3 tr\u1ed1ng \u0111\u1ec3 kh\xf3a v\xf4 th\u1eddi h\u1ea1n', null=True, verbose_name='H\u1ea1n kho\xe1 t\xe0i kho\u1ea3n')),
                ('avarta_url_full', models.URLField(blank=True, help_text='\u0110\u01b0\u1eddng d\u1eabn \u1ea3nh \u0111\u1ea1i di\u1ec7n. \u0110\u1ec3 tr\u1ed1ng \u0111\u1ec3 d\xf9ng \u1ea3nh m\u1eb7c \u0111\u1ecbnh', max_length=255, verbose_name='\u0110\u01b0\u1eddng d\u1eabn \u1ea3nh \u0111\u1ea1i di\u1ec7n')),
                ('avarta_url', models.URLField(blank=True, help_text='\u0110\u01b0\u1eddng d\u1eabn \u1ea3nh \u0111\u1ea1i di\u1ec7n thu nh\u1ecf. \u0110\u1ec3 tr\u1ed1ng \u0111\u1ec3 d\xf9ng \u1ea3nh m\u1eb7c \u0111\u1ecbnh', verbose_name='\u0110\u01b0\u1eddng d\u1eabn \u1ea3nh \u0111\u1ea1i di\u1ec7n thu nh\u1ecf')),
                ('failure_count', models.SmallIntegerField(default=0, help_text='S\u1ed1 l\u1ea7n \u0111\u0103ng nh\u1eadp l\u1ed7i. N\u1ebfu v\u01b0\u1ee3t qu\xe1 s\u1ed1 l\u1ea7n, s\u1ebd b\u1ecb kh\xf3a t\xe0i kho\u1ea3n', verbose_name='S\u1ed1 l\u1ea7n \u0111\u0103ng nh\u1eadp l\u1ed7i')),
                ('is_login_again_required', models.BooleanField(default=False, help_text='Y\xeau c\u1ea7u ng\u01b0\u1eddi d\xf9ng ph\u1ea3i \u0111\u0103ng nh\u1eadp l\u1ea1i.', verbose_name='Y\xeau c\u1ea7u ph\u1ea3i \u0111\u0103ng nh\u1eadp l\u1ea1i')),
                ('date_of_birth', models.DateField(blank=True, verbose_name='Ng\xe0y sinh')),
                ('family_name', models.CharField(help_text='H\u1ecd v\xe0 t\xean \u0111\u1ec7m', max_length=255, verbose_name='H\u1ecd')),
                ('name', models.CharField(max_length=255, verbose_name='T\xean')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='M\xf4 t\u1ea3')),
                ('address_1', models.CharField(blank=True, max_length=100, verbose_name='\u0110\u1ecba ch\u1ec9 1')),
                ('address_2', models.CharField(blank=True, max_length=100, verbose_name='\u0110\u1ecba ch\u1ec9 2')),
                ('address_3', models.CharField(blank=True, max_length=100, verbose_name='\u0110\u1ecba ch\u1ec9 3')),
                ('city', models.CharField(max_length=100, verbose_name='Th\xe0nh ph\u1ed1')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(blank=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('creator', models.ForeignKey(help_text='L\xe0 ng\u01b0\u1eddi d\xf9ng hi\u1ec7n t\u1ea1i', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
            ],
            options={
                'verbose_name': 'T\xe0i kho\u1ea3n',
            },
        ),
    ]
