# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'An Giang'), (1, 'B\xe0 R\u1ecba - V\u0169ng T\xe0u'), (2, 'B\u1ea1c Li\xeau'), (3, 'B\u1eafc Giang'), (4, 'B\u1eafc K\u1ea1n'), (5, 'B\u1eafc Ninh'), (6, 'B\u1ebfn Tre'), (7, 'B\xecnh D\u01b0\u01a1ng'), (8, 'B\xecnh \u0110\u1ecbnh'), (9, 'B\xecnh Ph\u01b0\u1edbc'), (10, 'B\xecnh Thu\u1eadn'), (11, 'C\xe0 Mau'), (12, 'Cao B\u1eb1ng'), (13, 'C\u1ea7n Th\u01a1'), (14, '\u0110\xe0 N\u1eb5ng'), (15, '\u0110\u1eafk L\u1eafk'), (16, '\u0110\u1eafk N\xf4ng'), (17, '\u0110i\u1ec7n Bi\xean'), (18, '\u0110\u1ed3ng Nai'), (19, '\u0110\u1ed3ng Th\xe1p'), (20, 'Gia Lai'), (21, 'H\xe0 Giang'), (22, 'H\xe0 Nam'), (23, 'H\xe0 N\u1ed9i'), (24, 'H\xe0 T\u0129nh'), (25, 'H\u1ea3i D\u01b0\u01a1ng'), (26, 'H\u1ea3i Ph\xf2ng'), (27, 'H\u1eadu Giang'), (28, 'H\xf2a B\xecnh'), (29, 'H\u01b0ng Y\xean'), (30, 'Kh\xe1nh H\xf2a'), (31, 'Ki\xean Giang'), (32, 'Kon Tum'), (33, 'Lai Ch\xe2u'), (34, 'L\u1ea1ng S\u01a1n'), (35, 'L\xe0o Cai'), (36, 'L\xe2m \u0110\u1ed3ng'), (37, 'Long An'), (38, 'Nam \u0110\u1ecbnh'), (39, 'Ngh\u1ec7 An'), (40, 'Ninh B\xecnh'), (41, 'Ninh Thu\u1eadn'), (42, 'Ph\xfa Th\u1ecd'), (43, 'Ph\xfa Y\xean'), (44, 'Qu\u1ea3ng B\xecnh'), (45, 'Qu\u1ea3ng Nam'), (46, 'Qu\u1ea3ng Ng\xe3i'), (47, 'Qu\u1ea3ng Ninh'), (48, 'Qu\u1ea3ng Tr\u1ecb'), (49, 'S\xf3c Tr\u0103ng'), (50, 'S\u01a1n La'), (51, 'T\xe2y Ninh'), (52, 'Th\xe1i B\xecnh'), (53, 'Th\xe1i Nguy\xean'), (54, 'Thanh H\xf3a'), (55, 'Th\u1eeba Thi\xean Hu\u1ebf'), (56, 'Ti\u1ec1n Giang'), (57, 'TP HCM'), (58, 'Tr\xe0 Vinh'), (59, 'Tuy\xean Quang'), (60, 'V\u0129nh Long'), (61, 'V\u0129nh Ph\xfac'), (62, 'Y\xean B\xe1i')], null=True, verbose_name='Th\xe0nh ph\u1ed1'),
        ),
    ]
