# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Ng\xe0y sinh'),
        ),
        migrations.AlterField(
            model_name='account',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt'),
        ),
    ]
