# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 02:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160710_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='creator',
            field=models.ForeignKey(help_text='L\xe0 ng\u01b0\u1eddi d\xf9ng hi\u1ec7n t\u1ea1i', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o'),
        ),
    ]
