# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 04:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
        ('outline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningDaySubjectSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('day_type', models.SmallIntegerField(choices=[(0, 'L\xfd thuy\u1ebft'), (1, 'Th\u1ea3o lu\u1eadn'), (2, 'T\u1ef1 h\u1ecdc')], default=0, verbose_name='Gi\u1edd')),
                ('day_of_week', models.SmallIntegerField(choices=[(0, 'Th\u1ee9 2'), (1, 'Th\u1ee9 3'), (2, 'Th\u1ee9 4'), (3, 'Th\u1ee9 5'), (4, 'Th\u1ee9 6'), (5, 'Th\u1ee9 7'), (6, 'Ch\u1ee7 nh\u1eadt')], verbose_name='Ng\xe0y trong tu\u1ea7n')),
                ('place', models.CharField(blank=True, max_length=100, verbose_name='N\u01a1i h\u1ecdc')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('lession_times', models.ManyToManyField(to='university.LessionTime', verbose_name='Ti\u1ebft h\u1ecdc')),
            ],
            options={
                'verbose_name': 'Ng\xe0y h\u1ecdc c\u1ee7a sinh vi\xean theo m\xf4n',
                'verbose_name_plural': 'Ng\xe0y h\u1ecdc c\u1ee7a sinh vi\xean theo m\xf4n',
            },
        ),
        migrations.CreateModel(
            name='LearningDaySubjectScheduleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('real_day', models.DateField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('learning_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.LearningDay')),
                ('learning_day_subject_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_schedule.LearningDaySubjectSchedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Semester', verbose_name='K\u1ef3 h\u1ecdc')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Student', verbose_name='Sinh vi\xean')),
            ],
            options={
                'verbose_name': 'L\u1ecbch h\u1ecdc sinh vi\xean',
                'verbose_name_plural': 'L\u1ecbch h\u1ecdc sinh vi\xean',
            },
        ),
        migrations.CreateModel(
            name='SubjectStudentSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('outline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outline.Outline', verbose_name='\u0110\u1ec1 c\u01b0\u01a1ng')),
                ('student_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_schedule.StudentSchedule', verbose_name='L\u1ecbch h\u1ecdc sinh vi\xean')),
                ('study_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.StudySession', verbose_name='\u0110\u1ee3t h\u1ecdc')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Subject', verbose_name='M\xf4n h\u1ecdc')),
            ],
            options={
                'verbose_name': 'L\u1ecbch h\u1ecdc sinh vi\xean theo m\xf4n',
                'verbose_name_plural': 'L\u1ecbch h\u1ecdc sinh vi\xean theo m\xf4n',
            },
        ),
        migrations.CreateModel(
            name='TempStudentScheduleGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('step', models.SmallIntegerField(default=1, verbose_name='B\u01b0\u1edbc')),
                ('done', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Student')),
                ('student_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_schedule.StudentSchedule')),
            ],
            options={
                'verbose_name': 'B\u1ea3ng t\u1ea1m qu\xe1 tr\xecnh t\u1ea1o l\u1ecbch h\u1ecdc sinh vi\xean. Ch\u1ecdn l\u1ecbch',
                'verbose_name_plural': 'B\u1ea3ng t\u1ea1m qu\xe1 tr\xecnh t\u1ea1o l\u1ecbch h\u1ecdc sinh vi\xean. Ch\u1ecdn l\u1ecbch',
            },
        ),
        migrations.CreateModel(
            name='TempSubjectStudentScheduleGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('outline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outline.Outline')),
                ('temp_student_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_schedule.TempStudentScheduleGenerator')),
            ],
            options={
                'verbose_name': 'B\u1ea3ng t\u1ea1m qu\xe1 tr\xecnh t\u1ea1o l\u1ecbch h\u1ecdc sinh vi\xean. Ch\u1ecdn \u0111\u1ec1 c\u01b0\u01a1ng',
                'verbose_name_plural': 'B\u1ea3ng t\u1ea1m qu\xe1 tr\xecnh t\u1ea1o l\u1ecbch h\u1ecdc sinh vi\xean. Ch\u1ecdn \u0111\u1ec1 c\u01b0\u01a1ng',
            },
        ),
        migrations.AddField(
            model_name='learningdaysubjectschedule',
            name='subject_student_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_schedule.SubjectStudentSchedule', verbose_name='Ng\xe0y h\u1ecdc'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectstudentschedule',
            unique_together=set([('student_schedule', 'subject')]),
        ),
    ]
