# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningdaysubjectschedule',
            options={'verbose_name': 'Ng\xe0y h\u1ecdc c\u1ee7a sinh vi\xean theo m\xf4n', 'verbose_name_plural': 'Ng\xe0y h\u1ecdc c\u1ee7a sinh vi\xean theo m\xf4n'},
        ),
        migrations.AlterField(
            model_name='studentschedule',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Semester', verbose_name='K\u1ef3 h\u1ecdc'),
        ),
    ]
