# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_schedule', '0002_auto_20161113_0127'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='tempstudentschedulegenerator',
        #     name='creator',
        # ),
        # migrations.RemoveField(
        #     model_name='tempstudentschedulegenerator',
        #     name='student_schedule',
        # ),
        # migrations.RemoveField(
        #     model_name='tempsubjectstudentschedulegenerator',
        #     name='creator',
        # ),
        # migrations.RemoveField(
        #     model_name='tempsubjectstudentschedulegenerator',
        #     name='outline',
        # ),
        # migrations.RemoveField(
        #     model_name='tempsubjectstudentschedulegenerator',
        #     name='subject_student_schedule',
        # ),
        # migrations.RemoveField(
        #     model_name='tempsubjectstudentschedulegenerator',
        #     name='temp_student_schedule',
        # ),
        # migrations.DeleteModel(
        #     name='TempStudentScheduleGenerator',
        # ),
        # migrations.DeleteModel(
        #     name='TempSubjectStudentScheduleGenerator',
        # ),
    ]
