# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_schedule', '0003_auto_20161113_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempStudentScheduleGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('step', models.SmallIntegerField(default=1, verbose_name='B\u01b0\u1edbc')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('student_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_schedule.StudentSchedule')),
            ],
            options={
                'verbose_name': 'B\u1ea3ng t\u1ea1m qu\xe1 tr\xecnh t\u1ea1o l\u1ecbch h\u1ecdc sinh vi\xean. Ch\u1ecdn l\u1ecbch',
                'verbose_name_plural': 'B\u1ea3ng t\u1ea1m qu\xe1 tr\xecnh t\u1ea1o l\u1ecbch h\u1ecdc sinh vi\xean. Ch\u1ecdn l\u1ecbch',
            },
        ),
        migrations.CreateModel(
            name='TempSubjectStudentScheduleGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('outline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outline.Outline')),
                ('subject_student_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_schedule.SubjectStudentSchedule')),
                ('temp_student_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_schedule.TempStudentScheduleGenerator')),
            ],
            options={
                'verbose_name': 'B\u1ea3ng t\u1ea1m qu\xe1 tr\xecnh t\u1ea1o l\u1ecbch h\u1ecdc sinh vi\xean. Ch\u1ecdn \u0111\u1ec1 c\u01b0\u01a1ng',
                'verbose_name_plural': 'B\u1ea3ng t\u1ea1m qu\xe1 tr\xecnh t\u1ea1o l\u1ecbch h\u1ecdc sinh vi\xean. Ch\u1ecdn \u0111\u1ec1 c\u01b0\u01a1ng',
            },
        ),
    ]
