# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-13 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_lessiontime'),
        ('student_schedule', '0004_tempstudentschedulegenerator_tempsubjectstudentschedulegenerator'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempstudentschedulegenerator',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tempstudentschedulegenerator',
            name='student_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_schedule.StudentSchedule'),
        ),
    ]
