# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-13 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_schedule', '0005_auto_20161113_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempstudentschedulegenerator',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
