# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-13 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_schedule', '0006_tempstudentschedulegenerator_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempsubjectstudentschedulegenerator',
            name='subject_student_schedule',
        ),
    ]
