# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-13 09:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.conf import settings
from django.utils.timezone import utc
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_schedule', '0007_remove_tempsubjectstudentschedulegenerator_subject_student_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningDaySubjectScheduleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('learning_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.LearningDay')),
                ('learning_day_subject_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_schedule.LearningDaySubjectSchedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='learningdaysubjectscheduledetail',
            name='real_day',
            field=models.DateField(default=datetime.datetime(2016, 11, 13, 9, 35, 20, 900000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
