# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0001_initial'),
        ('student_schedule', '0009_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectstudentschedule',
            name='outline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outline.Outline', verbose_name='\u0110\u1ec1 c\u01b0\u01a1ng'),
        ),
        migrations.AlterField(
            model_name='learningdaysubjectschedule',
            name='day_type',
            field=models.SmallIntegerField(choices=[(0, 'L\xfd thuy\u1ebft'), (1, 'Th\u1ea3o lu\u1eadn'), (2, 'T\u1ef1 h\u1ecdc')], default=0, verbose_name='Gi\u1edd'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectstudentschedule',
            unique_together=set([('student_schedule', 'subject')]),
        ),
    ]
