# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 04:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
        ('homework', '0001_initial'),
        ('outline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWorkAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('hwa_type', models.SmallIntegerField(choices=[(0, 'Nh\u1eadn'), (1, 'N\u1ed9p'), (2, 'Thuy\u1ebft tr\xecnh'), (3, 'L\xe0m')], default=0, verbose_name='Ho\u1ea1t \u0111\u1ed9ng')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.HomeWork', verbose_name='B\xe0i t\u1eadp')),
            ],
            options={
                'verbose_name': 'Ho\u1ea1t \u0111\u1ed9ng b\xe0i t\u1eadp',
                'verbose_name_plural': 'Ho\u1ea1t \u0111\u1ed9ng b\xe0i t\u1eadp',
            },
        ),
        migrations.CreateModel(
            name='LearningDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('week', models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)], verbose_name='S\u1ed1 th\u1ee9 t\u1ef1 c\u1ee7a tu\u1ea7n')),
                ('day_type', models.SmallIntegerField(choices=[(0, 'L\xfd thuy\u1ebft'), (1, 'Th\u1ea3o lu\u1eadn'), (2, 'T\u1ef1 h\u1ecdc')], verbose_name='Gi\u1edd')),
                ('order', models.SmallIntegerField(blank=True, choices=[(1, 1), (2, 2)], help_text='\u0110\u1ec3 tr\u1ed1ng n\u1ebfu ch\u1ec9 c\xf3 1 gi\u1edd', null=True, verbose_name='S\u1ed1')),
                ('day_order_of_week', models.SmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True, verbose_name='Th\u1ee9 t\u1ef1 h\u1ecdc trong tu\u1ea7n')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('subject_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.Outline', verbose_name='L\u1ecbch tr\xecnh h\u1ecdc h\xe0ng tu\u1ea7n')),
            ],
            options={
                'verbose_name': 'Ng\xe0y h\u1ecdc',
                'verbose_name_plural': 'Ng\xe0y h\u1ecdc',
            },
        ),
        migrations.CreateModel(
            name='LearningDayContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('content', models.CharField(max_length=255, verbose_name='N\u1ed9i dung')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.LearningDay', verbose_name='Ng\xe0y h\u1ecdc')),
            ],
            options={
                'verbose_name': 'N\u1ed9i dung h\u1ecdc',
                'verbose_name_plural': 'N\u1ed9i dung h\u1ecdc',
            },
        ),
        migrations.CreateModel(
            name='LearningDayRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('content', models.CharField(max_length=255, verbose_name='Y\xeau c\u1ea7u')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.LearningDay', verbose_name='Ng\xe0y h\u1ecdc')),
            ],
            options={
                'verbose_name': 'Y\xeau c\u1ea7u chu\u1ea9n b\u1ecb cho gi\u1edd h\u1ecdc',
                'verbose_name_plural': 'Y\xeau c\u1ea7u chu\u1ea9n b\u1ecb cho gi\u1edd h\u1ecdc',
            },
        ),
        migrations.CreateModel(
            name='Scholastic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('name', models.CharField(max_length=255, verbose_name='T\xean')),
                ('start_date', models.DateField(verbose_name='Ng\xe0y b\u1eaft \u0111\u1ea7u')),
                ('end_date', models.DateField(verbose_name='Ng\xe0y k\u1ebft th\xfac')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
            ],
            options={
                'verbose_name': 'N\u0103m h\u1ecdc',
                'verbose_name_plural': 'N\u0103m h\u1ecdc',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('order', models.SmallIntegerField(choices=[(1, 'K\u1ef3 1'), (2, 'K\u1ef3 2'), (3, 'K\u1ef3 3')], default=1, null=True, verbose_name='H\u1ecdc k\u1ef3')),
                ('start_date', models.DateField(blank=True, help_text='\u0110\u1ec3 tr\u1ed1ng n\u1ebfu tr\xf9ng v\u1edbi ng\xe0y c\u1ee7a n\u0103m h\u1ecdc', verbose_name='Ng\xe0y b\u1eaft \u0111\u1ea7u')),
                ('end_date', models.DateField(blank=True, help_text='\u0110\u1ec3 tr\u1ed1ng n\u1ebfu tr\xf9ng v\u1edbi ng\xe0y c\u1ee7a n\u0103m h\u1ecdc', verbose_name='Ng\xe0y k\u1ebft th\xfac')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('scholastic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Scholastic', verbose_name='N\u0103m h\u1ecdc')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.University', verbose_name='Tr\u01b0\u1eddng \u0111\u1ea1i h\u1ecdc')),
            ],
            options={
                'verbose_name': 'H\u1ecdc k\u1ef3',
                'verbose_name_plural': 'H\u1ecdc k\u1ef3',
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('order', models.SmallIntegerField(choices=[(None, None), (0, '15 tu\u1ea7n'), (1, 1), (2, 2), (3, 3)], default=None, help_text='\u0110\u1ec3 0 n\u1ebfu l\xe0 m\xf4n 15 tu\u1ea7n', verbose_name='\u0110\u1ee3t')),
                ('start_date', models.DateField(blank=True, help_text='\u0110\u1ec3 tr\u1ed1ng n\u1ebfu tr\xf9ng v\u1edbi ng\xe0y c\u1ee7a k\u1ef3 h\u1ecdc', verbose_name='Ng\xe0y b\u1eaft \u0111\u1ea7u')),
                ('end_date', models.DateField(blank=True, help_text='\u0110\u1ec3 tr\u1ed1ng n\u1ebfu tr\xf9ng v\u1edbi ng\xe0y c\u1ee7a k\u1ef3 h\u1ecdc', verbose_name='Ng\xe0y k\u1ebft th\xfac')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Semester', verbose_name='H\u1ecdc k\u1ef3')),
            ],
            options={
                'verbose_name': '\u0110\u1ee3t h\u1ecdc',
                'verbose_name_plural': '\u0110\u1ee3t h\u1ecdc',
            },
        ),
        migrations.CreateModel(
            name='SubjectSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('week', models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)], verbose_name='S\u1ed1 th\u1ee9 t\u1ef1 c\u1ee7a tu\u1ea7n')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.Outline', verbose_name='\u0110\u1ec1 c\u01b0\u01a1ng')),
            ],
            options={
                'verbose_name': 'L\u1ecbch tr\xecnh h\u1ecdc h\xe0ng tu\u1ea7n',
                'verbose_name_plural': 'L\u1ecbch tr\xecnh h\u1ecdc h\xe0ng tu\u1ea7n',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('start_date', models.DateField(verbose_name='Ng\xe0y b\u1eaft \u0111\u1ea7u')),
                ('end_date', models.DateField(verbose_name='Ng\xe0y k\u1ebft th\xfac')),
                ('order', models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)], verbose_name='S\u1ed1 th\u1ee9 t\u1ef1 c\u1ee7a tu\u1ea7n')),
                ('other_order', models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='S\u1ed1 th\u1ee9 t\u1ef1 c\u1ee7a m\xf4n 5 tu\u1ea7n')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Semester', verbose_name='H\u1ecdc k\u1ef3')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='homeworkaction',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Week', verbose_name='Tu\u1ea7n'),
        ),
    ]
