# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20161115_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='holiday',
            field=models.BooleanField(default=False, verbose_name='Tu\u1ea7n l\u1ec5'),
        ),
        migrations.AlterField(
            model_name='week',
            name='other_order',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='S\u1ed1 th\u1ee9 t\u1ef1 c\u1ee7a m\xf4n 5 tu\u1ea7n'),
        ),
    ]
