# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-05 14:05
from __future__ import unicode_literals

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkquestion',
            name='description',
            field=common.models.DescriptionField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeworkquestionattachment',
            name='description',
            field=common.models.DescriptionField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeworksolution',
            name='description',
            field=common.models.DescriptionField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeworksolutionattachment',
            name='description',
            field=common.models.DescriptionField(blank=True, max_length=255, null=True),
        ),
    ]
