# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_auto_20161105_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkquestion',
            name='content',
            field=models.CharField(blank=True, max_length=500, verbose_name='N\u1ed9i dung'),
        ),
        migrations.AlterField(
            model_name='homeworkquestion',
            name='no',
            field=models.CharField(blank=True, help_text='S\u1ed1 th\u1ee9 t\u1ef1 \u0111\u1ec1. \u0110\u1ec3 0 n\u1ebfu kh\xf4ng x\xe1c \u0111\u1ecbnh', max_length=50, verbose_name='\u0110\u1ec1'),
        ),
    ]
