# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import homework.validators


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_auto_20161109_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeworkquestionattachment',
            options={'verbose_name': 'File \u0111\xednh k\xe8m \u0111\u1ec1 b\xe0i t\u1eadp', 'verbose_name_plural': 'File \u0111\xednh k\xe8m \u0111\u1ec1 b\xe0i t\u1eadp'},
        ),
        migrations.AlterField(
            model_name='homeworkquestion',
            name='no',
            field=models.CharField(blank=True, help_text='S\u1ed1 th\u1ee9 t\u1ef1 \u0111\u1ec1. \u0110\u1ec3 0 n\u1ebfu kh\xf4ng x\xe1c \u0111\u1ecbnh. <br />N\u1ebfu \u0111\u1ec1 b\xe0i thay \u0111\u1ed5i theo l\u1edbp, vui l\xf2ng ghi t\xean l\u1edbp v\xe0o', max_length=50, verbose_name='\u0110\u1ec1'),
        ),
        migrations.AlterField(
            model_name='homeworkquestionattachment',
            name='document',
            field=models.FileField(max_length=200, upload_to='questions/%Y/%m/%d/', validators=[homework.validators.validate_homework_file_extension], verbose_name='HomeWork Question'),
        ),
        migrations.AlterField(
            model_name='homeworksolutionattachment',
            name='document',
            field=models.FileField(max_length=200, upload_to='solutions/%Y/%m/%d/', validators=[homework.validators.validate_homework_file_extension], verbose_name='HomeWork Solution'),
        ),
    ]
