# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 04:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('day_of_week', models.SmallIntegerField(choices=[(0, 'Th\u1ee9 2'), (1, 'Th\u1ee9 3'), (2, 'Th\u1ee9 4'), (3, 'Th\u1ee9 5'), (4, 'Th\u1ee9 6'), (5, 'Th\u1ee9 7'), (6, 'Ch\u1ee7 nh\u1eadt')], verbose_name='Ng\xe0y')),
                ('start_time', models.TimeField(blank=True, verbose_name='B\u1eaft \u0111\u1ea7u')),
                ('end_time', models.TimeField(blank=True, verbose_name='K\u1ebft th\xfac')),
                ('place', models.CharField(blank=True, max_length=255, verbose_name='\u0110\u1ecba \u0111i\u1ec3m')),
            ],
            options={
                'verbose_name': 'Th\u1eddi gian t\u01b0 v\u1ea5n',
                'verbose_name_plural': 'Th\u1eddi gian t\u01b0 v\u1ea5n',
            },
        ),
        migrations.CreateModel(
            name='Outline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('study_time_type', models.SmallIntegerField(choices=[(0, '15 tu\u1ea7n'), (1, '5 tu\u1ea7n')], default=0, verbose_name='Tu\u1ea7n h\u1ecdc')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.Course', verbose_name='Kh\xf3a')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
            ],
            options={
                'verbose_name': '\u0110\u1ec1 c\u01b0\u01a1ng',
                'verbose_name_plural': '\u0110\u1ec1 c\u01b0\u01a1ng',
            },
        ),
        migrations.CreateModel(
            name='OutlineLearningResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('resource_type', models.SmallIntegerField(choices=[(0, 'B\u1eaft bu\u1ed9c'), (1, 'Tham kh\u1ea3o')], default=0, verbose_name='Lo\u1ea1i t\xe0i li\u1ec7u')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('learning_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.LearningResource', verbose_name='H\u1ecdc li\u1ec7u')),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.Outline', verbose_name='\u0110\u1ec1 c\u01b0\u01a1ng')),
            ],
            options={
                'verbose_name': 'T\xe0i li\u1ec7u cho m\xf4n h\u1ecdc',
                'verbose_name_plural': 'T\xe0i li\u1ec7u cho m\xf4n h\u1ecdc',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('name', models.CharField(max_length=255, verbose_name='T\xean v\u1ea5n \u0111\u1ec1')),
                ('order', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)], verbose_name='S\u1ed1')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.Outline', verbose_name='\u0110\u1ec1 c\u01b0\u01a1ng')),
            ],
            options={
                'verbose_name': 'V\u1ea5n \u0111\u1ec1',
                'verbose_name_plural': 'V\u1ea5n \u0111\u1ec1',
            },
        ),
        migrations.CreateModel(
            name='ProblemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('content', models.CharField(max_length=255, verbose_name='N\u1ed9i dung v\u1ea5n \u0111\u1ec1')),
                ('order', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='S\u1ed1')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.Problem', verbose_name='V\u1ea5n \u0111\u1ec1')),
            ],
            options={
                'verbose_name': 'N\u1ed9i dung v\u1ea5n \u0111\u1ec1',
                'verbose_name_plural': 'N\u1ed9i dung v\u1ea5n \u0111\u1ec1',
            },
        ),
        migrations.CreateModel(
            name='TargetAwareness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('level', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], verbose_name='B\u1eadc')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outline.Problem', verbose_name='V\u1ea5n \u0111\u1ec1')),
                ('problem_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outline.ProblemDetail', verbose_name='V\u1ea5n \u0111\u1ec1 chi ti\u1ebft')),
            ],
            options={
                'verbose_name': 'M\u1ee5c ti\xeau nh\u1eadn th\u1ee9c',
                'verbose_name_plural': 'M\u1ee5c ti\xeau nh\u1eadn th\u1ee9c',
            },
        ),
        migrations.CreateModel(
            name='TargetAwarenessDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('order', models.SmallIntegerField(verbose_name='Th\u1ee9 t\u1ef1')),
                ('content', models.TextField(max_length=500, verbose_name='N\u1ed9i dung')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('target_awareness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.TargetAwareness', verbose_name='M\u1ee9c ti\xeau nh\u1eadn th\u1ee9c')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
