# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 04:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
        ('outline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outline',
            name='study_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.StudySession', verbose_name='\u0110\u1ee3t h\u1ecdc'),
        ),
        migrations.AddField(
            model_name='outline',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Subject', verbose_name='M\xf4n h\u1ecdc'),
        ),
        migrations.AddField(
            model_name='advisorytime',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o'),
        ),
        migrations.AddField(
            model_name='advisorytime',
            name='outline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.Outline', verbose_name='\u0110\u1ec1 c\u01b0\u01a1ng'),
        ),
    ]
