# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-05 13:23
from __future__ import unicode_literals

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='T\xean')),
                ('name_abbr', models.CharField(blank=True, max_length=255, verbose_name='T\xean vi\u1ebft t\u1eaft')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('description', common.models.DescriptionField(blank=True, max_length=255, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
            ],
            options={
                'verbose_name': 'Kho\xe1',
                'verbose_name_plural': 'Kho\xe1',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='T\xean')),
                ('name_abbr', models.CharField(blank=True, max_length=255, verbose_name='T\xean vi\u1ebft t\u1eaft')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='\u0110\u1ecba ch\u1ec9')),
                ('description', common.models.DescriptionField(blank=True, max_length=255, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
            ],
            options={
                'verbose_name': 'Khoa',
                'verbose_name_plural': 'Khoa',
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('nick_name', models.CharField(blank=True, max_length=255, verbose_name='Bi\u1ec7t hi\u1ec7u')),
                ('description', common.models.DescriptionField(blank=True, max_length=255, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_account', to=settings.AUTH_USER_MODEL, verbose_name='T\xe0i kho\u1ea3n')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Gi\u1ea3ng vi\xean',
                'verbose_name_plural': 'Gi\u1ea3ng vi\xean',
            },
        ),
        migrations.CreateModel(
            name='Scholastic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('name', models.CharField(max_length=255, verbose_name='T\xean')),
                ('start_date', models.DateField(verbose_name='Ng\xe0y b\u1eaft \u0111\u1ea7u')),
                ('end_date', models.DateField(verbose_name='Ng\xe0y k\u1ebft th\xfac')),
                ('description', common.models.DescriptionField(blank=True, max_length=255, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
            ],
            options={
                'verbose_name': 'N\u0103m h\u1ecdc',
                'verbose_name_plural': 'N\u0103m h\u1ecdc',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('order', models.SmallIntegerField(choices=[(1, 'K\u1ef3 1'), (2, 'K\u1ef3 2')], default=1, null=True, verbose_name='H\u1ecdc k\u1ef3')),
                ('start_date', models.DateField(blank=True, help_text='\u0110\u1ec3 tr\u1ed1ng n\u1ebfu tr\xf9ng v\u1edbi ng\xe0y c\u1ee7a n\u0103m h\u1ecdc', verbose_name='Ng\xe0y b\u1eaft \u0111\u1ea7u')),
                ('end_date', models.DateField(blank=True, help_text='\u0110\u1ec3 tr\u1ed1ng n\u1ebfu tr\xf9ng v\u1edbi ng\xe0y c\u1ee7a n\u0103m h\u1ecdc', verbose_name='Ng\xe0y k\u1ebft th\xfac')),
                ('description', common.models.DescriptionField(blank=True, max_length=255, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('scholastic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Scholastic', verbose_name='N\u0103m h\u1ecdc')),
            ],
            options={
                'verbose_name': 'H\u1ecdc k\u1ef3',
                'verbose_name_plural': 'H\u1ecdc k\u1ef3',
            },
        ),
        migrations.CreateModel(
            name='SpecializedStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='T\xean')),
                ('name_abbr', models.CharField(blank=True, max_length=255, verbose_name='T\xean vi\u1ebft t\u1eaft')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='\u0110\u1ecba ch\u1ec9')),
                ('description', common.models.DescriptionField(blank=True, max_length=255, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('faculty', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='university.Faculty', verbose_name='Khoa')),
            ],
            options={
                'verbose_name': 'B\u1ed9 m\xf4n',
                'verbose_name_plural': 'B\u1ed9 m\xf4n',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('nick_name', models.CharField(blank=True, max_length=255, verbose_name='Bi\u1ec7t hi\u1ec7u')),
                ('description', common.models.DescriptionField(blank=True, max_length=255, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_account', to=settings.AUTH_USER_MODEL, verbose_name='T\xe0i kho\u1ea3n')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
            ],
            options={
                'verbose_name': 'Sinh vi\xean',
                'verbose_name_plural': 'Sinh vi\xean',
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('order', models.SmallIntegerField(choices=[(None, None), (0, '15 tu\u1ea7n'), (1, 1), (2, 2), (3, 3)], default=None, help_text='\u0110\u1ec3 0 n\u1ebfu l\xe0 m\xf4n 15 tu\u1ea7n', verbose_name='\u0110\u1ee3t')),
                ('start_date', models.DateField(blank=True, help_text='\u0110\u1ec3 tr\u1ed1ng n\u1ebfu tr\xf9ng v\u1edbi ng\xe0y c\u1ee7a k\u1ef3 h\u1ecdc', verbose_name='Ng\xe0y b\u1eaft \u0111\u1ea7u')),
                ('end_date', models.DateField(blank=True, help_text='\u0110\u1ec3 tr\u1ed1ng n\u1ebfu tr\xf9ng v\u1edbi ng\xe0y c\u1ee7a k\u1ef3 h\u1ecdc', verbose_name='Ng\xe0y k\u1ebft th\xfac')),
                ('description', common.models.DescriptionField(blank=True, max_length=255, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Semester', verbose_name='H\u1ecdc k\u1ef3')),
            ],
            options={
                'verbose_name': '\u0110\u1ee3t h\u1ecdc',
                'verbose_name_plural': '\u0110\u1ee3t h\u1ecdc',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='T\xean')),
                ('name_abbr', models.CharField(blank=True, max_length=255, verbose_name='T\xean vi\u1ebft t\u1eaft')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('credit', models.SmallIntegerField(choices=[(1, '1 t\xedn ch\u1ec9'), (2, '2 t\xedn ch\u1ec9'), (3, '3 t\xedn ch\u1ec9'), (4, '4 t\xedn ch\u1ec9'), (5, '5 t\xedn ch\u1ec9')], default=2, verbose_name='S\u1ed1 t\xedn ch\u1ec9')),
                ('description', common.models.DescriptionField(blank=True, max_length=255, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('specialized_study', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='university.SpecializedStudy', verbose_name='B\u1ed9 m\xf4n')),
            ],
            options={
                'verbose_name': 'M\xf4n h\u1ecdc',
                'verbose_name_plural': 'M\xf4n h\u1ecdc',
            },
        ),
        migrations.CreateModel(
            name='UClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='T\xean')),
                ('name_abbr', models.CharField(blank=True, max_length=255, verbose_name='T\xean vi\u1ebft t\u1eaft')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('description', common.models.DescriptionField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Course', verbose_name='Kho\xe1')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
            ],
            options={
                'verbose_name': 'L\u1edbp',
                'verbose_name_plural': 'L\u1edbp',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='T\xean')),
                ('name_abbr', models.CharField(blank=True, max_length=255, verbose_name='T\xean vi\u1ebft t\u1eaft')),
                ('address_1', models.CharField(blank=True, max_length=100, verbose_name='\u0110\u1ecba ch\u1ec9 1')),
                ('address_2', models.CharField(blank=True, max_length=100, verbose_name='\u0110\u1ecba ch\u1ec9 2')),
                ('address_3', models.CharField(blank=True, max_length=100, verbose_name='\u0110\u1ecba ch\u1ec9 3')),
                ('city', models.SmallIntegerField(choices=[(0, 'An Giang'), (1, 'B\xe0 R\u1ecba - V\u0169ng T\xe0u'), (2, 'B\u1ea1c Li\xeau'), (3, 'B\u1eafc Giang'), (4, 'B\u1eafc K\u1ea1n'), (5, 'B\u1eafc Ninh'), (6, 'B\u1ebfn Tre'), (7, 'B\xecnh D\u01b0\u01a1ng'), (8, 'B\xecnh \u0110\u1ecbnh'), (9, 'B\xecnh Ph\u01b0\u1edbc'), (10, 'B\xecnh Thu\u1eadn'), (11, 'C\xe0 Mau'), (12, 'Cao B\u1eb1ng'), (13, 'C\u1ea7n Th\u01a1'), (14, '\u0110\xe0 N\u1eb5ng'), (15, '\u0110\u1eafk L\u1eafk'), (16, '\u0110\u1eafk N\xf4ng'), (17, '\u0110i\u1ec7n Bi\xean'), (18, '\u0110\u1ed3ng Nai'), (19, '\u0110\u1ed3ng Th\xe1p'), (20, 'Gia Lai'), (21, 'H\xe0 Giang'), (22, 'H\xe0 Nam'), (23, 'H\xe0 N\u1ed9i'), (24, 'H\xe0 T\u0129nh'), (25, 'H\u1ea3i D\u01b0\u01a1ng'), (26, 'H\u1ea3i Ph\xf2ng'), (27, 'H\u1eadu Giang'), (28, 'H\xf2a B\xecnh'), (29, 'H\u01b0ng Y\xean'), (30, 'Kh\xe1nh H\xf2a'), (31, 'Ki\xean Giang'), (32, 'Kon Tum'), (33, 'Lai Ch\xe2u'), (34, 'L\u1ea1ng S\u01a1n'), (35, 'L\xe0o Cai'), (36, 'L\xe2m \u0110\u1ed3ng'), (37, 'Long An'), (38, 'Nam \u0110\u1ecbnh'), (39, 'Ngh\u1ec7 An'), (40, 'Ninh B\xecnh'), (41, 'Ninh Thu\u1eadn'), (42, 'Ph\xfa Th\u1ecd'), (43, 'Ph\xfa Y\xean'), (44, 'Qu\u1ea3ng B\xecnh'), (45, 'Qu\u1ea3ng Nam'), (46, 'Qu\u1ea3ng Ng\xe3i'), (47, 'Qu\u1ea3ng Ninh'), (48, 'Qu\u1ea3ng Tr\u1ecb'), (49, 'S\xf3c Tr\u0103ng'), (50, 'S\u01a1n La'), (51, 'T\xe2y Ninh'), (52, 'Th\xe1i B\xecnh'), (53, 'Th\xe1i Nguy\xean'), (54, 'Thanh H\xf3a'), (55, 'Th\u1eeba Thi\xean Hu\u1ebf'), (56, 'Ti\u1ec1n Giang'), (57, 'TP HCM'), (58, 'Tr\xe0 Vinh'), (59, 'Tuy\xean Quang'), (60, 'V\u0129nh Long'), (61, 'V\u0129nh Ph\xfac'), (62, 'Y\xean B\xe1i')], null=True, verbose_name='Th\xe0nh ph\u1ed1')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('founding', models.DateField(verbose_name='Ng\xe0y th\xe0nh l\u1eadp')),
                ('description', common.models.DescriptionField(blank=True, max_length=255, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
            ],
            options={
                'verbose_name': '\u0110\u1ea1i h\u1ecdc',
                'verbose_name_plural': '\u0110\u1ea1i h\u1ecdc',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='u_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.UClass', verbose_name='L\u1edbp'),
        ),
        migrations.AddField(
            model_name='specializedstudy',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.University', verbose_name='Tr\u01b0\u1eddng \u0111\u1ea1i h\u1ecdc'),
        ),
        migrations.AddField(
            model_name='semester',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.University', verbose_name='Tr\u01b0\u1eddng \u0111\u1ea1i h\u1ecdc'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.University', verbose_name='Tr\u01b0\u1eddng \u0111\u1ea1i h\u1ecdc'),
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.University', verbose_name='Tr\u01b0\u1eddng \u0111\u1ea1i h\u1ecdc'),
        ),
    ]
