# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 03:51
from __future__ import unicode_literals

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessionTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('name', models.CharField(max_length=10, verbose_name='Ti\u1ebft h\u1ecdc')),
                ('order', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14)], verbose_name='Th\u1ee9 t\u1ef1')),
                ('description', common.models.DescriptionField(blank=True, max_length=255, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.University', verbose_name='\u0110\u1ea1i h\u1ecdc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, max_length=25, verbose_name='M\xe3 sinh vi\xean'),
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=25, verbose_name='M\xe3 m\xf4n h\u1ecdc'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='order',
            field=models.SmallIntegerField(choices=[(1, 'K\u1ef3 1'), (2, 'K\u1ef3 2'), (3, 'K\u1ef3 3')], default=1, null=True, verbose_name='H\u1ecdc k\u1ef3'),
        ),
    ]
