# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 18:21
from __future__ import unicode_literals

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0002_auto_20161113_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessionTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Th\u1eddi gian t\u1ea1o')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt')),
                ('name', models.CharField(blank=True, max_length=10, verbose_name='Ti\u1ebft h\u1ecdc')),
                ('start', models.TimeField(verbose_name='B\u1eaft \u0111\u1ea7u')),
                ('end', models.TimeField(help_text='Th\u1eddi gian k\u1ebft th\xfac ph\u1ea3i nh\u1ecf h\u01a1n th\u1eddi gian b\u1eaft \u0111\u1ea7u', verbose_name='k\u1ebft th\xfac')),
                ('order', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14)], verbose_name='Th\u1ee9 t\u1ef1')),
                ('description', common.models.DescriptionField(blank=True, max_length=255, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ng\u01b0\u1eddi t\u1ea1o')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.University', verbose_name='\u0110\u1ea1i h\u1ecdc')),
            ],
            options={
                'verbose_name': 'Ti\u1ebft h\u1ecdc',
                'verbose_name_plural': 'Ti\u1ebft h\u1ecdc',
            },
        ),
    ]
