# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20161111_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessiontime',
            options={'verbose_name': 'Ti\u1ebft h\u1ecdc', 'verbose_name_plural': 'Ti\u1ebft h\u1ecdc'},
        ),
        migrations.AlterField(
            model_name='lessiontime',
            name='name',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ti\u1ebft h\u1ecdc'),
        ),
    ]
