# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20160710_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt'),
        ),
        migrations.AlterField(
            model_name='scholastic',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt'),
        ),
        migrations.AlterField(
            model_name='specializedstudy',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt'),
        ),
        migrations.AlterField(
            model_name='uclass',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt'),
        ),
        migrations.AlterField(
            model_name='university',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Th\u1eddi gian c\u1eadp nh\u1eadt'),
        ),
    ]
