# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20161115_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='founding',
            field=models.DateField(blank=True, null=True, verbose_name='Ng\xe0y th\xe0nh l\u1eadp'),
        ),
    ]
