# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20161111_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessiontime',
            name='end',
            field=models.DateTimeField(default='2016-11-11 10:00', help_text='Th\u1eddi gian k\u1ebft th\xfac ph\u1ea3i nh\u1ecf h\u01a1n th\u1eddi gian b\u1eaft \u0111\u1ea7u', verbose_name='k\u1ebft th\xfac'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessiontime',
            name='start',
            field=models.DateTimeField(default='2016-11-11 10:00', verbose_name='B\u1eaft \u0111\u1ea7u'),
            preserve_default=False,
        ),
    ]
