# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20160710_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specializedstudy',
            old_name='address_1',
            new_name='address',
        ),
    ]
