# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_auto_20160710_1625'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lecturer',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='scholastic',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='specializedstudy',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='uclass',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='university',
            name='deleted',
        ),
        migrations.AddField(
            model_name='course',
            name='alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scholastic',
            name='alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='specializedstudy',
            name='alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uclass',
            name='alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='university',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
