# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_lessiontime'),
        ('university', '0005_auto_20161111_1134'),
    ]

    operations = [
    ]
