# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_auto_20160710_1647'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lecturer',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='alive',
        ),
        migrations.RemoveField(
            model_name='scholastic',
            name='alive',
        ),
        migrations.RemoveField(
            model_name='specializedstudy',
            name='alive',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='alive',
        ),
        migrations.RemoveField(
            model_name='uclass',
            name='alive',
        ),
        migrations.RemoveField(
            model_name='university',
            name='alive',
        ),
        migrations.AddField(
            model_name='course',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='scholastic',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='specializedstudy',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='uclass',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
